services:
  api:
    build: ./backend
    container_name: fluxo-api
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql+asyncpg://fluxo:fluxo@postgres:5432/fluxo
      - DATABASE_URL_SYNC=postgresql+psycopg2://fluxo:fluxo@postgres:5432/fluxo
      - SECRET_KEY=ae9600e53cbccaaedb0c3f0400e13d81a764a0c013d77d068b4662d66c00468d
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=525600
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: fluxo-postgres-1
    restart: always
    environment:
      POSTGRES_USER: fluxo
      POSTGRES_PASSWORD: fluxo
      POSTGRES_DB: fluxo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: fluxo-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fluxo.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
